### ISSUE TITLE
使用uclient-fetch无法更新core 但是使用curl可以

### ISSUE THREAD

**Issue by sirstrone** [immortalwrt/luci-app-unblockneteasemusic#143]
更新Core的时候
![image](https://user-images.githubusercontent.com/30281719/162755629-295e7eba-f27d-48d8-bb84-dde1563945ab.png)
提示 
Failed to check latest core version, please try again later.
看了一下Log 是由于无法下载commits version导致的

Package: libustream-mbedtls20201210
Version: 2022-01-16-868fd881-1
Depends: libc, libubox20211120, libmbedtls12
Provides: libustream-mbedtls
Conflicts: libustream-openssl, libustream-wolfssl
Status: unknown ok not-installed
Section: libs
Architecture: x86_64
Size: 5338
Filename: libustream-mbedtls20201210_2022-01-16-868fd881-1_x86_64.ipk
Description: ustream SSL Library (mbedtls)

Downloading 'https://api.github.com/repos/UnblockNeteaseMusic/server/commits?sha=enhanced&path=precompiled'
Connecting to :::443
Connection error: Connection failed
Failed to parse json data: unexpected end of data
Failed to connect to GitHub with uclient-fetch.

实测了一下 本地对github的链接和证书没问题的 路由器里也安装了对应的
libustream-openssl20201210 依赖

相同环境下 使用curl 获取这个link 是正常的 
![image](https://user-images.githubusercontent.com/30281719/162754900-a905a836-378f-4cdb-a6bb-d0baa3bc8659.png)

重装问题依旧存在

作者大大帮忙看下问题可能出在哪

Lede版本:
Linux OpenWrt 5.15.32 #0 SMP Sun Apr 10 08:32:25 2022 x86_64 GNU/Linux
使用coolsnowwolf大佬的lede编译的

**Comment by 1715173329** [comment]
日志不全。
本机 DNS 解析有问题。

**Comment by Jieoz** [comment]
老哥最后怎么解决的，改脚本吗
