### ISSUE TITLE
此前安装的CA证书在访问斗鱼,bilibili子域名时出现安全问题

### ISSUE THREAD

**Issue by zzz6839** [immortalwrt/luci-app-unblockneteasemusic#226]
### Bug 描述

当我使用EDGE浏览器ver.108.0.1462.54 访问www.douyu.com和登陆bilibili时会访问https://passport.bilibili.cn， 此时**有概率**出现网页连接不安全提示，问题指向是此前安装的ca.cert证书，请问是什么情况？

### 复现步骤

访问网页www.douyu.com会有一定概率出现此问题，
或者登陆bilibili，手机短信验证登陆之后，在https://passport.bilibili.cn 页面下会出现安全问题，随后刷新bilibili主页后显示已经正常登陆。

### 日志内容

<img width="546" alt="certificate" src="https://user-images.githubusercontent.com/57741549/210554360-b2cc0027-5460-4565-8bb0-78c077d61fe0.png">
<img width="1139" alt="error bili" src="https://user-images.githubusercontent.com/57741549/210554366-fd6185db-c403-40d7-8858-27c84d7fbb37.png">
<img width="1149" alt="error log douyu" src="https://user-images.githubusercontent.com/57741549/210554368-af024c16-217d-4e8d-a853-b3c5449333ba.png">

### 网易云音乐版本号

2.10.6(Build:200601)(Patch:1:c6adf94)

### 操作系统

win11 22621.963

### 条款

- [X] 我确认我使用的核心是由 UnblockNeteaseMusic 项目官方发行，不是其他任何 fork。
- [X] 我确认我已经升级到了最新的核心版本（推荐使用最新构建而不是 release）。
- [X] 我确认我已经启用了 HTTPS 端口。
- [X] 我确认我已经正确设置了 EndPoint（仅 macOS 或 iOS）。
- [X] 我确认我已经在对应的客户端正确安装了 CA 证书。
- [X] 我同意开发者没有任何义务必须解答我的问题，尤其是缺少恰当的描述和日志。

**Comment by 1715173329** [comment]
本插件不能解决。你可以自行用 clash 规则劫持，但是不能让本机也走规则，否则会回环。
