### ISSUE TITLE
打开"部署到公网"和"严格模式"后防火墙重启会卡死

### ISSUE THREAD

**Issue by pikachullk** [immortalwrt/luci-app-unblockneteasemusic#46]
重启第一次防火墙可以
root@ImmortalWrt:~# service firewall restart
Warning: Section @defaults[0] requires unavailable target extension FLOWOFFLOAD, disabling
Warning: Section @defaults[0] requires unavailable target extension FLOWOFFLOAD, disabling
 * Flushing IPv4 filter table
 * Flushing IPv4 nat table
 * Flushing IPv4 mangle table
 * Flushing IPv4 raw table
 * Flushing IPv6 filter table
 * Flushing IPv6 nat table
 * Flushing IPv6 mangle table
 * Flushing conntrack table ...
 * Populating IPv4 filter table
   * Rule 'Allow-DHCP-Renew'
   * Rule 'Allow-Ping'
   * Rule 'Allow-IGMP'
   * Rule 'Allow-IPSec-ESP'
   * Rule 'Allow-ISAKMP'
   * Rule 'adblock'
   * Forward 'lan' -> 'wan'
   * Zone 'lan'
   * Zone 'wan'
 * Populating IPv4 nat table
   * Zone 'lan'
   * Zone 'wan'
Warning: wan will enable FULLCONE-NAT
 * Populating IPv4 mangle table
   * Zone 'lan'
   * Zone 'wan'
 * Populating IPv4 raw table
   * Zone 'lan'
     - Using automatic conntrack helper attachment
   * Zone 'wan'
 * Populating IPv6 filter table
   * Rule 'Allow-DHCPv6'
   * Rule 'Allow-MLD'
   * Rule 'Allow-ICMPv6-Input'
   * Rule 'Allow-ICMPv6-Forward'
   * Rule 'Allow-IPSec-ESP'
   * Rule 'Allow-ISAKMP'
   * Rule 'adblock'
   * Forward 'lan' -> 'wan'
   * Zone 'lan'
   * Zone 'wan'
 * Populating IPv6 nat table
Warning: fw3_ipt_rule_append(): Can't find target 'prerouting_lan_rule'
Warning: fw3_ipt_rule_append(): Can't find target 'postrouting_lan_rule'
Warning: fw3_ipt_rule_append(): Can't find target 'prerouting_wan_rule'
Warning: fw3_ipt_rule_append(): Can't find target 'postrouting_wan_rule'
Warning: fw3_ipt_rule_append(): Can't find target 'prerouting_rule'
Warning: fw3_ipt_rule_append(): Can't find target 'postrouting_rule'
   * Zone 'lan'
   * Zone 'wan'
 * Populating IPv6 mangle table
   * Zone 'lan'
   * Zone 'wan'
 * Set tcp_ecn to off
 * Set tcp_syncookies to on
 * Set tcp_window_scaling to on
 * Running script '/etc/firewall.user'
 * Running script '/etc/zerotier.start'
 * Running script '/usr/share/miniupnpd/firewall.include'
 * Running script '/var/etc/adbyby.include'
   ! Skipping due to path error: No such file or directory
 * Running script '/var/etc/shadowsocksr.include'
 * Running script '/etc/mia.include'
 * Running script '/var/etc/unblockneteasemusic.include'
 * Running script '/var/etc/openclash.include'
root@ImmortalWrt:~# service firewall restart

,第二次重启的时候就会卡死在那,这会导致端口转发在openclash重启或者是重新拨号以后端口转发失效...
不知道是不是自己编译的时候有什么没有选择

**Comment by QiuSimons** [comment]
好像没遇到这种情况过。你是在用友善wrt，或者koolshare之类的么？

**Comment by pikachullk** [comment]
> 好像没遇到这种情况过。你是在用友善wrt，或者koolshare之类的么？

我是用的sora的源码啊~是18.04-k5.4的

**Comment by QiuSimons** [comment]
晚点我试试看

**Comment by pikachullk** [comment]
> 晚点我试试看

我刚刚还试了一下,仅仅打开部署到公网就有这个情况了

**Comment by QiuSimons** [comment]
没有复现诶

**Comment by pikachullk** [comment]
> 没有复现诶

呃.....难道是我用的版本有问题...

**Comment by pikachullk** [comment]
> 没有复现诶

大佬~我现在重新编译了一次,刚刚刷完机~只开openclash的redir-host和网易云也会这样啊....这个会和IPV6有关系吗?

**Comment by pikachullk** [comment]
> 没有复现诶

我附上我编译的.config吧~麻烦大佬帮忙看看
https://raw.githubusercontent.com/pikachullk/OpenWrt-CI/master/.config

**Comment by pikachullk** [comment]
> 没有复现诶

就我的意思是连续输入两次/etc/init.d/firewall restart...第二次会没有反应

**Comment by pikachullk** [comment]
看了一下核心的issue,好像是核心 -s本身的bug导致的～无解了
