### ISSUE TITLE
网易云插件无法启动 

### ISSUE THREAD

**Issue by jiuxiajingfan** [immortalwrt/luci-app-unblockneteasemusic#48]
日志内容
Error: getaddrinfo ENOTFOUND httpdns.n.netease.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'httpdns.n.netease.com'
}

**Comment by 1715173329** [comment]
你 DNS 炸了。

**Comment by h6fYe34KFSiH** [comment]
是不是用了 smartdns？和我的报错一样
