### ISSUE TITLE
周杰伦的歌还是不灰但是无法播放

### ISSUE THREAD

**Issue by sayikaqaq** [immortalwrt/luci-app-unblockneteasemusic#50]

**Comment by 1715173329** [comment]
本项目不接算命业务

**Comment by sayikaqaq** [comment]
其他灰色歌曲都能正常播放，一些估计来源是qq音乐的源对不上。要么无法播放，要么是歌曲和歌曲名字是乱的。平台是改版lede homelede。网易云版本2.8.0软件，组件也都是最新。

**Comment by 1715173329** [comment]
估计？什么是估计？你都估计完了还需要提 issue？还需要日志？
QQ 音乐没填 VIP cookie 你还想用？

**Comment by sayikaqaq** [comment]
好凶啊，解决了。谢谢

**Comment by ElonH** [comment]
@sayikaqaq 我是萌新～～～
