### ISSUE TITLE
启动报错确认这边DNS没有问题

### ISSUE THREAD

**Issue by JSZMonkey** [immortalwrt/luci-app-unblockneteasemusic#51]
Error: getaddrinfo ENOTFOUND httpdns.n.netease.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'httpdns.n.netease.com'
}

**Comment by 1715173329** [comment]
@JSZMonkey 不要你确认，你 DNS 没问题不会报这个错。

**Comment by JSZMonkey** [comment]
刚才在路由里用诊断工具nslookup了一下 确认是 无法解析 httpdns.n.netease.com 这个IP 已经在AD里面 DNS 重写了
