### ISSUE TITLE
大佬我想请问下如果挂载在op上 电脑端可以正常解锁  安卓端无法解锁该如何操作

### ISSUE THREAD

**Issue by jiuxiajingfan** [immortalwrt/luci-app-unblockneteasemusic#53]
![image](https://user-images.githubusercontent.com/69376042/116784799-bd3ced80-aac8-11eb-841b-22582c813562.png)
MITM > api2.music.163.com 
MITM > apm3.music.163.com 
MITM > clientlog3.music.163.com 
MITM > clientlog3.music.163.com 
MITM > clientlog3.music.163.com 
MITM > clientlog.music.163.com 
MITM > clientlog3.music.163.com 
MITM > music.163.com 
MITM > interface3.music.163.com 
MITM > interface3.music.163.com 
MITM > interface3.music.163.com 
MITM > interface3.music.163.com 
MITM > interface3.music.163.com 
MITM > api2.music.163.com 
MITM > apm3.music.163.com 
MITM > clientlog3.music.163.com 
MITM > clientlog3.music.163.com 
MITM > interface3.music.163.com 
MITM > clientlog3.music.163.com 
MITM > clientlog3.music.163.com 
MITM > clientlog3.music.163.com

**Comment by 1715173329** [comment]
信任证书。

**Comment by jiuxiajingfan** [comment]
感谢我尝试下
