### ISSUE TITLE
手机访问页面路由unblockneteasemusic管理页面403

### ISSUE THREAD

**Issue by JSZMonkey** [immortalwrt/luci-app-unblockneteasemusic#54]
Request URL: http://openwrt.lan/cgi-bin/luci/admin/services/unblockneteasemusic
Request Method: GET
Status Code: 403 Forbidden
Remote Address: 192.168.0.1:80
Referrer Policy: strict-origin-when-cross-origin
Connection: Keep-Alive
Keep-Alive: timeout=20
Transfer-Encoding: chunked
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Accept-Encoding: gzip, deflate
Accept-Language: zh-CN,zh;q=0.9
Cache-Control: no-cache
Connection: keep-alive
Cookie: sysauth=b157fd6ae7c7c1acfed1271bdd4d12db
Host: openwrt.lan
Pragma: no-cache
Referer: http://openwrt.lan/cgi-bin/luci/
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Linux; Android 6.0.1; Moto G (4)) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Mobile Safari/537.36

**Comment by 1715173329** [comment]
配置呢？

**Comment by JSZMonkey** [comment]
默认配置什么都没改 简单模式

**Comment by 1715173329** [comment]
建议从自身找问题，报错内容和本插件无关。
