### ISSUE TITLE
win10系统，网易云音乐版本2.8.0 无法解锁，但是安卓和IOS版可以正常解锁，请问大家都这样吗？

### ISSUE THREAD

**Issue by michealhansun** [immortalwrt/luci-app-unblockneteasemusic#56]
win10系统，网易云音乐版本2.8.0 无法解锁，但是安卓和IOS版可以正常解锁，请问大家都这样吗？

**Comment by EnnawYang** [comment]
2.8.0(198822)解锁正常

**Comment by 1715173329** [comment]
No log no solution.

**Comment by michealhansun** [comment]
发现问题了：EndPoint 我改成了：https://music.163.com; ios才能播放，当时windows不能播放，改成http://music.163.com的话，windows能播放，ios不能播放，只能在用什么设备的时候手动修改了

**Comment by 1715173329** [comment]
我没有兴趣再单独为了 iOS 开个独立的进程。
另外我测试 Windows PC 2.2.2 版本是可以用 https endpoint 的。

**Comment by 1715173329** [comment]
现在已经实现了自适应，使用 HTTPS endpoint 时，pc 及 uwp 会自动降级为 HTTP。

**Comment by michealhansun** [comment]
好像不能直接更新，请问是否需要编译最新版重新安装吗？

**Comment by 1715173329** [comment]
y

**Comment by michealhansun** [comment]
给大佬个反馈，现在可以 IOS 安卓 win 三个系统一起使用了，谢谢大佬适配
