### ISSUE TITLE
无法hook 目标地址?

### ISSUE THREAD

**Issue by peterpei1186861238** [immortalwrt/luci-app-unblockneteasemusic#57]
```
/usr/share/unblockneteasemusic/core/src/app.js:59
const target = Array.from(hook.target.host)
                                      ^

TypeError: Cannot read property 'host' of undefined
    at Object.<anonymous> (/usr/share/unblockneteasemusic/core/src/app.js:59:39)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/share/unblockneteasemusic/core/app.js:2:1)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
```

**Comment by 1715173329** [comment]
DNS 解析问题

**Comment by zlf179** [comment]
我也遇到这个问题啦 不过我解决了 方法如下 问题并不是DNS解析出问题了 而是hook.js里面该有的内容没了
1. 用winscp进入/usr/share/unblockneteasemusic/core/src/目录 然后有个hook.js文件 拖到桌面上来
2. 浏览器打开https://github.com/nondanee/UnblockNeteaseMusic，打开同路径下的hook.js文件
3. 复制其中所有内容，notepad打开js添加到桌面刚复制的hook.js文件中，并保存
4. 用桌面的js文件替换路由器中的文件
5. 路由管理界面重新打开网易云插件
6. enjoy， 问题解决 错误不再

**Comment by zlf179** [comment]
> ```
> /usr/share/unblockneteasemusic/core/src/app.js:59
> const target = Array.from(hook.target.host)
>                                       ^
> 
> TypeError: Cannot read property 'host' of undefined
>     at Object.<anonymous> (/usr/share/unblockneteasemusic/core/src/app.js:59:39)
>     at Module._compile (internal/modules/cjs/loader.js:1137:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
>     at Module.load (internal/modules/cjs/loader.js:985:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:878:14)
>     at Module.require (internal/modules/cjs/loader.js:1025:19)
>     at require (internal/modules/cjs/helpers.js:72:18)
>     at Object.<anonymous> (/usr/share/unblockneteasemusic/core/app.js:2:1)
>     at Module._compile (internal/modules/cjs/loader.js:1137:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
> ```

我也遇到这个问题啦 不过我解决了 方法如下 问题并不是DNS解析出问题了 而是hook.js里面该有的内容没了

用winscp进入/usr/share/unblockneteasemusic/core/src/目录 然后有个hook.js文件 拖到桌面上来
浏览器打开https://github.com/nondanee/UnblockNeteaseMusic，打开同路径下的hook.js文件
复制其中所有内容，notepad打开js添加到桌面刚复制的hook.js文件中，并保存
用桌面的js文件替换路由器中的文件
路由管理界面重新打开网易云插件
enjoy， 问题解决 错误不再

**Comment by peterpei1186861238** [comment]
> 
> 
> > ```
> > /usr/share/unblockneteasemusic/core/src/app.js:59
> > const target = Array.from(hook.target.host)
> >                                       ^
> > 
> > TypeError: Cannot read property 'host' of undefined
> >     at Object.<anonymous> (/usr/share/unblockneteasemusic/core/src/app.js:59:39)
> >     at Module._compile (internal/modules/cjs/loader.js:1137:30)
> >     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
> >     at Module.load (internal/modules/cjs/loader.js:985:32)
> >     at Function.Module._load (internal/modules/cjs/loader.js:878:14)
> >     at Module.require (internal/modules/cjs/loader.js:1025:19)
> >     at require (internal/modules/cjs/helpers.js:72:18)
> >     at Object.<anonymous> (/usr/share/unblockneteasemusic/core/app.js:2:1)
> >     at Module._compile (internal/modules/cjs/loader.js:1137:30)
> >     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
> > ```
> 
> 我也遇到这个问题啦 不过我解决了 方法如下 问题并不是DNS解析出问题了 而是hook.js里面该有的内容没了
> 
> 用winscp进入/usr/share/unblockneteasemusic/core/src/目录 然后有个hook.js文件 拖到桌面上来
> 浏览器打开[https://github.com/nondanee/UnblockNeteaseMusic，打开同路径下的hook.js文件](https://github.com/nondanee/UnblockNeteaseMusic%EF%BC%8C%E6%89%93%E5%BC%80%E5%90%8C%E8%B7%AF%E5%BE%84%E4%B8%8B%E7%9A%84hook.js%E6%96%87%E4%BB%B6)
> 复制其中所有内容，notepad打开js添加到桌面刚复制的hook.js文件中，并保存
> 用桌面的js文件替换路由器中的文件
> 路由管理界面重新打开网易云插件
> enjoy， 问题解决 错误不再

感谢，已解决

**Comment by 1715173329** [comment]
问题好了的原因是 DNS 解析正常了而已
会有玄学问题导致无法解析
至于替换，这两个文件内容一模一样
