### ISSUE TITLE
开启本插件后会影响部分网站访问和passwall代理

### ISSUE THREAD

**Issue by feileb** [immortalwrt/luci-app-unblockneteasemusic#59]
1，目前发现虎牙和斗鱼两个网站证书不正确，chrome无法访问，firefox可以正常访问
huya.com
douyu.com

2，影响passwall全局代理，估计也是证书问题
passwall代理gfwlist的网站访问非常慢，关掉网易云插件后可以正常代理

**Comment by 1715173329** [comment]
也许是你开的什么插件冲突了，我从来没遇到过这种情况
关于你说的导致其他网站证书错误，我也曾在其他几个人身上见过（不同网站），不清楚是什么问题

btw，我使用 openclash 和 ssrplus。

**Comment by feileb** [comment]
未访问网易云音乐的时候，如果访问网站异常，在日志里面也可以看到类似下面的日志：
MITM > interface.music.163.com 
MITM > interface.music.163.com 
MITM > interface.music.163.com 

另外不知道这个插件是怎么劫持网易云音乐的流量的，防火墙规则里面好像没有看到
