### ISSUE TITLE
插件要自己编译才能安装吗？

### ISSUE THREAD

**Issue by Chu2koi** [immortalwrt/luci-app-unblockneteasemusic#61]
我下载了release里的ipk，但是安装失败，显示failed code 255
![2021-06-19_020847](https://user-images.githubusercontent.com/12667784/122601406-d4995f80-d0a3-11eb-95a8-12f26d6069cc.png)

**Comment by 1715173329** [comment]
You're missing the dependencies, check them in Makefile.
