### ISSUE TITLE
5.10编译完成启动正常，日志报错

### ISSUE THREAD

**Issue by MrFubO** [immortalwrt/luci-app-unblockneteasemusic#64]
Fri Jul  9 14:10:00 2021 cron.err crond[27199]: USER root pid 30797 cmd /usr/share/unblockneteasemusic/log_check.sh
Fri Jul  9 14:15:00 2021 cron.err crond[27199]: USER root pid 1590 cmd /usr/share/unblockneteasemusic/log_check.sh
Fri Jul  9 14:20:00 2021 cron.err crond[27199]: USER root pid 4374 cmd /usr/share/unblockneteasemusic/log_check.sh
Fri Jul  9 14:25:00 2021 cron.err crond[27199]: USER root pid 6710 cmd /usr/share/unblockneteasemusic/log_check.sh
Fri Jul  9 14:30:00 2021 cron.err crond[27199]: USER root pid 7983 cmd /usr/share/unblockneteasemusic/log_check.sh
Fri Jul  9 14:34:03 2021 cron.err crond[9713]: crond (busybox 1.33.1) started, log level 5
Fri Jul  9 14:34:03 2021 cron.err crond[10035]: crond (busybox 1.33.1) started, log level 5
Fri Jul  9 14:34:04 2021 cron.err crond[10349]: crond (busybox 1.33.1) started, log level 5
Fri Jul  9 14:35:00 2021 cron.err crond[10349]: USER root pid 10750 cmd /usr/share/unblockneteasemusic/log_check.sh
Fri Jul  9 14:40:00 2021 cron.err crond[10349]: USER root pid 12452 cmd /usr/share/unblockneteasemusic/log_check.sh

系统日志里5分钟报错一次，启动的时候正常，也能替换音源
更新组件页面只有更新主程序，无更新luCL选项
请问是哪里出错了？

**Comment by 1715173329** [comment]
这不是报错，是 crond 的问题
