### ISSUE TITLE
unblockneteasemusic未运行

### ISSUE THREAD

**Issue by yezivvvv** [immortalwrt/luci-app-unblockneteasemusic#65]
OPENWRT，内核版本：5.10.50，unblockneteasemusic未运行

卸载重装或者删掉/usr/share/unblockneteasemusic/都试过了还是不行，望解答，感谢。
日志：SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at /usr/share/unblockneteasemusic/core/src/request.js:89:64
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Promise.all (index 1)

**Comment by 1715173329** [comment]
I cannot reproduce this error, check your network etc.

**Comment by yezivvvv** [comment]
[](url)

**Comment by yezivvvv** [comment]
![网页捕获](https://user-images.githubusercontent.com/31228933/126252175-11c6297c-a76c-46c8-80a0-a483c0359743.jpeg)

**Comment by 1715173329** [comment]
This firmware is not supported.
