### ISSUE TITLE
使用IPSet/hosts的方式进行劫持会导致云音乐无法使用

### ISSUE THREAD

**Issue by jiajiaxd** [immortalwrt/luci-app-unblockneteasemusic#70]
使用IPSet/hosts的方式进行劫持会导致云音乐无法联网
这导致我不能打开劫持，然后只有电脑的网易云客户端可以使用unblock-netease-music，因为电脑版支持设置代理

**Comment by 1715173329** [comment]
本项目不提供算命服务。
