### ISSUE TITLE
报错 无法运行 已升级最新 2.10

### ISSUE THREAD

**Issue by yer2018** [immortalwrt/luci-app-unblockneteasemusic#71]
/usr/share/unblockneteasemusic/core/src/hook.js:409
		if ((item.code != 200 || item.freeTrialInfo) && (target == 0 || item.id == target)) {
		^^

SyntaxError: Unexpected token 'if'
    at wrapSafe (internal/modules/cjs/loader.js:1053:16)
    at Module._compile (internal/modules/cjs/loader.js:1101:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/share/unblockneteasemusic/core/src/app.js:82:14)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)

**Comment by zzz6839** [comment]
+1， mini的版本也只能部分解锁歌曲

我2.10版本还是一样的错误（X86_64）openwrt 18.06.9, Powered by LuCI Master (git-21.211.30217-03784c3)

**Comment by 1715173329** [comment]
你需要删掉核心，重新下载

**Comment by zzz6839** [comment]
> 你需要删掉核心，重新下载

能给个卸载核心的教程吗，我只会卸载luci-app-neteasemusic的安装包，小白求助

**Comment by Beginner-Go** [comment]
cd /
rm -rf usr/share/unblockneteasemusic/core*

**Comment by zzz6839** [comment]
> cd /
> rm -rf usr/share/unblockneteasemusic/core*

it worked! love u❤

**Comment by yer2018** [comment]
删掉 核心 重新 安装 搞定了。多谢

**Comment by greedisgoood** [comment]
> 删掉 核心 重新 安装 搞定了。多谢

重新安装ipk的吗？   我核心卸载就启动不了

**Comment by zzz6839** [comment]
> > 删掉 核心 重新 安装 搞定了。多谢
> 
> 重新安装ipk的吗？ 我核心卸载就启动不了

卸载当前版本 opkg remove luci-app-unblockneteasemusic +版本
卸载核心
cd /
rm -rf usr/share/unblockneteasemusic/core
安装最新版本 opkg install luci-app-unblockneteasemusic + 最新版本
然后到更新组件页面更新核心就可以了

**Comment by greedisgoood** [comment]
> > > 删掉 核心 重新 安装 搞定了。多谢
> > 
> > 
> > 重新安装ipk的吗？ 我核心卸载就启动不了
> 
> 卸载当前版本 opkg remove luci-app-unblockneteasemusic +版本
> 卸载核心
> cd /
> rm -rf usr/share/unblockneteasemusic/core
> 安装最新版本 opkg install luci-app-unblockneteasemusic + 最新版本
> 然后到更新组件页面更新核心就可以了

很遗憾，照步骤进行，卸载核心以后使用最新版安装，更新组件页面只有更新主程序，
日志显示：Failed to check latest core version, please try again later.
Core Not Found, please download it before starting.

**Comment by zzz6839** [comment]
> > > > 删掉 核心 重新 安装 搞定了。多谢
> > > 
> > > 
> > > 重新安装ipk的吗？ 我核心卸载就启动不了
> > 
> > 
> > 卸载当前版本 opkg remove luci-app-unblockneteasemusic +版本
> > 卸载核心
> > cd /
> > rm -rf usr/share/unblockneteasemusic/core
> > 安装最新版本 opkg install luci-app-unblockneteasemusic + 最新版本
> > 然后到更新组件页面更新核心就可以了
> 
> 很遗憾，照步骤进行，卸载核心以后使用最新版安装，更新组件页面只有更新主程序，
> 日志显示：Failed to check latest core version, please try again later.
> Core Not Found, please download it before starting.

应该是你网络问题导致的更新失败，上不可描述更新

**Comment by greedisgoood** [comment]
> > > > > 删掉 核心 重新 安装 搞定了。多谢
> > > > 
> > > > 
> > > > 重新安装ipk的吗？ 我核心卸载就启动不了
> > > 
> > > 
> > > 卸载当前版本 opkg remove luci-app-unblockneteasemusic +版本
> > > 卸载核心
> > > cd /
> > > rm -rf usr/share/unblockneteasemusic/core
> > > 安装最新版本 opkg install luci-app-unblockneteasemusic + 最新版本
> > > 然后到更新组件页面更新核心就可以了
> > 
> > 
> > 很遗憾，照步骤进行，卸载核心以后使用最新版安装，更新组件页面只有更新主程序，
> > 日志显示：Failed to check latest core version, please try again later.
> > Core Not Found, please download it before starting.
> 
> 应该是你网络问题导致的更新失败，上不可描述更新

该设备当前网络已不可描述，我再找找原因。感谢回复

**Comment by ASFLY61** [comment]
> > > > > > 删掉 核心 重新 安装 搞定了。多谢
> > > > > 
> > > > > 
> > > > > 重新安装ipk的吗？ 我核心卸载就启动不了
> > > > 
> > > > 
> > > > 卸载当前版本 opkg remove luci-app-unblockneteasemusic +版本
> > > > 卸载核心
> > > > cd /
> > > > rm -rf usr/share/unblockneteasemusic/core
> > > > 安装最新版本 opkg install luci-app-unblockneteasemusic + 最新版本
> > > > 然后到更新组件页面更新核心就可以了
> > > 
> > > 
> > > 很遗憾，照步骤进行，卸载核心以后使用最新版安装，更新组件页面只有更新主程序，
> > > 日志显示：Failed to check latest core version, please try again later.
> > > Core Not Found, please download it before starting.
> > 
> > 
> > 应该是你网络问题导致的更新失败，上不可描述更新
> 
> 该设备当前网络已不可描述，我再找找原因。感谢回复

我 的也是提示这个了，，你这边这边找到原因了吗

**Comment by 1715173329** [comment]
There were too many breaking changes made by upstream... Please don't upgrade the core.
If you did that alreadly, please be patient and wait for fixes.

**Comment by 1715173329** [comment]
See https://github.com/immortalwrt/luci-app-unblockneteasemusic/releases/tag/v2.10-2.

**Comment by zlr1** [comment]
> > > > > > > 删掉 核心 重新 安装 搞定了。多谢
> > > > > > 
> > > > > > 
> > > > > > 伊夫伊普克， ？
> > > > > 
> > > > > 
> > > > > 19 00 下一个 opkg 删除 luci -  app  -  unlocknetease 音乐 + 19 - rf usr / 股票 / 解开网状音乐 / 核心opkg 安装luci - app - unblocknetease 音乐 + 1
> > > > 
> > > > 
> > > > ， 核心未找到，请在开始之前下载。
> > > 
> > > 
> > > 应该是你网络问题导致的更新失败，上不可描述更新
> > 
> > 
> > 该设备当前网络已不可描述，我再找找原因。感谢回复
> 
> 我 的也是提示这个了，，你这边这边找到原因了吗
已找到问题，点击更新提示最新版本。但内核没有更新。只需删除/usr/share/unblockneteasemusic/下的core_local_ver文件再点击更新即可解决

**Comment by michealhansun** [comment]
我的目录下没有/usr/share/unblockneteasemusic/下的core_local_ver文件，
