### ISSUE TITLE
安卓客户端无法使用，Mac客户端正常使用

### ISSUE THREAD

**Issue by Nyaasu66** [immortalwrt/luci-app-unblockneteasemusic#73]
### 安卓设备：

机型：Redmi K40

Android 版本：11

系统版本：MIUI 12.5.4 稳定版

网易云版本：8.2.31.220755

是否已安装CA根证书：是

### Mac设备：

网易云版本：2.3.5

是否已安装CA根证书：是

### luci-app 配置：

音源接口：默认

劫持方法：使用IPSet劫持（不开启的话2个客户端均无法正常解锁歌曲）

其他均为默认配置

### luci-app 日志

```
HTTP Server running @ http://192.168.40.1:5200
HTTPS Server running @ http://192.168.40.1:5201
```

**Comment by EnnawYang** [comment]
客户端请不要用新版本，6.0正常使用

**Comment by Nyaasu66** [comment]
> 客户端请不要用新版本，6.0正常使用

好的谢谢，那我关issue了

**Comment by Nyaasu66** [comment]
> 客户端请不要用新版本，6.0正常使用

我在 [豌豆荚历史版本](https://www.wandoujia.com/apps/293217/history) 里下载安装了 `6.0.0` 版本，仍然无法正常使用，mac正常。

**Comment by Nyaasu66** [comment]
没事了，重启了下手机就好了））

**Comment by WROIATE** [comment]
请问不能使用新版是什么原因呢？现在已经实现mac、windows、ios都能解锁，唯独安卓失败
