### ISSUE TITLE
/usr/share/unblockneteasemusic/core/src/hook.js 408行有错误

### ISSUE THREAD

**Issue by FR-Chelsea** [immortalwrt/luci-app-unblockneteasemusic#74]
408行if有错误代码
// if (
// 	(item.code != 200 || item.freeTrialInfo) &&
// if ((item.code != 200 || item.freeTrialInfo) && (target == 0 || item.id == target)) {
// ) {
		
if ((item.code != 200 || item.freeTrialInfo) && (target == 0 || item.id == target)) 
		 {

**Comment by 1715173329** [comment]
#71
