### ISSUE TITLE
音源接口不能设置为“默认”，无法启动

### ISSUE THREAD

**Issue by EnnawYang** [immortalwrt/luci-app-unblockneteasemusic#75]
```
usage: unblockneteasemusic [-v] [-p port] [-a address] [-u url] [-f host]
                           [-o source [source ...]] [-t token] [-e url] [-s]
                           [-h]
unblockneteasemusic: error: extra arguments found: default
```
指定音源接口不报错，可以启动

**Comment by bili-guigui** [comment]
这个问题我解决hook.js的问题后就出现了，不过不一样的是 我的是无法启动。
usage: unblockneteasemusic [-v] [-p port] [-a address] [-u url] [-f host]
                           [-o source [source ...]] [-t token] [-e url] [-s]
                           [-h]
unblockneteasemusic: error: extra arguments found: default

**Comment by 1715173329** [comment]
Yes... I forgot to unset `music_source` in this case....
I will fix this later in the day.
