### ISSUE TITLE
更新到最新版本无法启动

### ISSUE THREAD

**Issue by keeno1982** [immortalwrt/luci-app-unblockneteasemusic#77]
已经是拉了最新的版本 954e95760b90ba786ff4ffd27368d72d2fbb26ca 重新编译的，仍然启动不了，查看日志那一栏也看不到任何信息

查看系统日志报错如下：
Sun Aug 22 21:16:53 2021 daemon.err uhttpd[2136]: cat: can't open '/usr/share/unblockneteasemusic/core_local_ver': No such file or directory

**Comment by lxl6125** [comment]
/usr/share/unblockneteasemusic/core/src/app.js:85
const target = Array.from(hook.target.host);
                                      ^

TypeError: Cannot read property 'host' of undefined
    at Object.<anonymous> (/usr/share/unblockneteasemusic/core/src/app.js:85:39)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/usr/share/unblockneteasemusic/core/app.js:2:1)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)

**Comment by keeno1982** [comment]
> 
> 
> /usr/share/unblockneteasemusic/core/src/app.js:85
> const target = Array.from(hook.target.host);
> ^
> 
> TypeError: Cannot read property 'host' of undefined
> at Object. (/usr/share/unblockneteasemusic/core/src/app.js:85:39)
> at Module._compile (internal/modules/cjs/loader.js:1072:14)
> at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
> at Module.load (internal/modules/cjs/loader.js:937:32)
> at Function.Module._load (internal/modules/cjs/loader.js:778:12)
> at Module.require (internal/modules/cjs/loader.js:961:19)
> at require (internal/modules/cjs/helpers.js:92:18)
> at Object. (/usr/share/unblockneteasemusic/core/app.js:2:1)
> at Module._compile (internal/modules/cjs/loader.js:1072:14)
> at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)

这是什么意思呢？

**Comment by lxl6125** [comment]
> > /usr/share/unblockneteasemusic/core/src/app.js:85
> > const target = Array.from(hook.target.host);
> > ^
> > TypeError: Cannot read property 'host' of undefined
> > at Object. (/usr/share/unblockneteasemusic/core/src/app.js:85:39)
> > at Module._compile (internal/modules/cjs/loader.js:1072:14)
> > at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
> > at Module.load (internal/modules/cjs/loader.js:937:32)
> > at Function.Module._load (internal/modules/cjs/loader.js:778:12)
> > at Module.require (internal/modules/cjs/loader.js:961:19)
> > at require (internal/modules/cjs/helpers.js:92:18)
> > at Object. (/usr/share/unblockneteasemusic/core/app.js:2:1)
> > at Module._compile (internal/modules/cjs/loader.js:1072:14)
> > at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
> 
> 这是什么意思呢？

错误日志，我也是无法启动

**Comment by keeno1982** [comment]
请教一下如何退到前面的版本

**Comment by 1715173329** [comment]
删除 /usr/share/unblockneteasemusic 文件夹，重装插件。

**Comment by 1715173329** [comment]
哦对了，配置文件格式改了，不能用原来的。

**Comment by keeno1982** [comment]
还是不行，看来UnblockNeteaseMusic有区分大小写的目录，是不是写错地方了，照样是会生成两个目录

**Comment by keeno1982** [comment]
@1715173329 issue别着急关啊老大，问题还没解决，着你说的做同样是启动不了

**Comment by EnnawYang** [comment]
什么？还不能启动？

![Snipaste_2021-08-23_10-14-09](https://user-images.githubusercontent.com/6705663/130380831-152ab5cb-3d80-4cdc-a20c-4330d50d6141.png)

**Comment by QiuSimons** [comment]
> @1715173329 issue别着急关啊老大，问题还没解决，着你说的做同样是启动不了

删配置文件，删除core

**Comment by keeno1982** [comment]
> 
> 
> > @1715173329 issue别着急关啊老大，问题还没解决，着你说的做同样是启动不了
> 
> 删配置文件，删除core

删了，还是启动不了

**Comment by keeno1982** [comment]
再次拉取今天最新的代码编译225fd05adc30b76bd3edeead93e8eb5f294143a8，点击删除核心，然后再更新核心，仍然无法启动，奇怪了
![FireShot Capture 020](https://user-images.githubusercontent.com/13664097/130474240-dc7e9cfa-8ff3-45d8-9374-75391d252050.png)

**Comment by msylgj** [comment]
@keeno1982 原来的配置文件也要删除 /etc/config/unblockneteasemusic  另外截这个图有什么用, 日志里面的内容呢? 那个才有用

**Comment by keeno1982** [comment]
> 
> 
> @keeno1982 原来的配置文件也要删除 /etc/config/unblockneteasemusic 另外截这个图有什么用, 日志里面的内容呢? 那个才有用

原来如此，删掉后重装果然可以了，非常感谢！截这张图是因为日志栏一直是空的。
