### ISSUE TITLE
启动后无法解锁

### ISSUE THREAD

**Issue by Xunflash** [immortalwrt/luci-app-unblockneteasemusic#79]
日志：
HTTP Server running @ http://192.168.1.2:5200
HTTPS Server running @ http://192.168.1.2:5201
MITM > null 
MITM > null 
MITM > null 
MITM > null 
MITM > apm.music.163.com 
MITM > apm.music.163.com 

设备：
树莓派4b，做的单臂旁路由，wan口lan口共用

版本：
![image](https://user-images.githubusercontent.com/71567536/130635247-c0ec645f-e47f-40cd-9b38-bc0e196b9749.png)
插件最新版

具体情况：
开启插件后，所有设备（Windows，安卓）无法解锁灰色歌曲，网易云音乐pc版把代理设置为192.168.1.2：5200后音源有误

起初以为是openclash冲突导致，关闭后依然是相同的情况，树莓派上面只挂了一个frpc和网页

能否帮忙分析 一下什么情况，谢谢

**Comment by gurongwei** [comment]
单臂旁路由是个什么玩意

**Comment by Xunflash** [comment]
> 单臂旁路由是个什么玩意

就是无线AP兼做交换机，全改成lan口，然后把树莓派wan，lan设置成一个口

**Comment by hecarli555** [comment]
> 单臂旁路由是个什么玩意

就是旁路由，全称叫单臂旁路由，我插件新版，用的爱快虚拟op，op作为旁路由，打够启动解锁歌曲了，保存并应有好提示未运行

**Comment by 1715173329** [comment]
本项目不为“旁路由”提供任何支持。
