### ISSUE TITLE
安装问题

### ISSUE THREAD

**Issue by TomyJan** [immortalwrt/luci-app-unblockneteasemusic#81]
大佬,安装遇到如下问题

```
root@LEDE:~# opkg install 1.ipk
Installing luci-app-unblockneteasemusic (2.10-3) to root...
Multiple packages (libstdcpp and libstdcpp) providing same name marked HOLD or PREFER. Using latest.
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for luci-app-unblockneteasemusic:
 * 	libustream-openssl20201210
 * opkg_install_cmd: Cannot install package luci-app-unblockneteasemusic.
```

请问如何解决?搜索了下说是因为软件包冲突,但是也找不到详细方案了

系统是 ` LEDE Reboot 17.01-SNAPSHOT r4046-beaa2ecc10 `

**Comment by 1715173329** [comment]
> LEDE Reboot 17.01-SNAPSHOT r4046-beaa2ecc10

It's too old.
Using `opkg install --nodeps` may help.

**Comment by TomyJan** [comment]
> opkg install --nodeps

感谢,安装成功了

但现在无法启动...提示下载失败,请问该如何解决
![image](https://user-images.githubusercontent.com/67973160/131834728-f479da47-fc05-4967-b1a9-e204539b365d.png)

**Comment by 1715173329** [comment]
自己装 libustream-ssl

**Comment by TomyJan** [comment]
> 自己装 libustream-ssl

还是不行...
