### ISSUE TITLE
重新安装后无法更新核心

### ISSUE THREAD

**Issue by kun526586** [immortalwrt/luci-app-unblockneteasemusic#83]
Failed to check latest core version, please try again later.
Core Not Found, please download it before starting.
核心和配置删除重装后显示这个，更新提示当前已是最新版本。

**Comment by 1715173329** [comment]
Remove the core and re-download.

**Comment by kun526586** [comment]
![1111](https://user-images.githubusercontent.com/62023524/132317921-bda0c30c-9abd-4d93-a846-789ea1c5ef28.png)
删除完核心重装还是这样

**Comment by 1715173329** [comment]
Check your network then.

**Comment by kun526586** [comment]
网络正常还是不可以，拿另一台没安装过旧版本的同样路由器直接装新版本就可以使用。

**Comment by 1715173329** [comment]
Pls compile this package yourself.
The pre-compile ipk in "latest release" is not the newest.

**Comment by kun526586** [comment]
好吧 ‘’自己编译这个包‘’不懂怎么弄，不弄了，还是谢谢你  麻烦了。

**Comment by WROIATE** [comment]
> Pls compile this package yourself.
> The pre-compiled ipk in "latest release" is not the newest.

查出来一个bug，好像是源名称更换了导致的
![image](https://user-images.githubusercontent.com/44677306/133934520-427e4a79-c6dd-435e-bdee-30739101f63f.png)
@kun526586 
我看最新源码好像已经在十小时前更新修复了，你可以重编译看看

**Comment by 1715173329** [comment]
现在已经设置 actions 自动构建 ipk 包。

**Comment by kun526586** [comment]
我用另一个路由安装后把文件替换给这个路由就可以用啦~
