### ISSUE TITLE
OpenWrt 21.02版本编译依赖冲突

### ISSUE THREAD

**Issue by Neutralization** [immortalwrt/luci-app-unblockneteasemusic#89]
OpenWrt 21.02.0版本NanoPi R2S默认依赖项是 libustream-wolfssl
unblockneteasemusic中的Makefile中依赖项是 libustream-openssl
直接编译会发生冲突，替换Makefile的依赖为libustream-wolfssl可正常编译。

**Comment by 1715173329** [comment]
建议把默认的 wolfssl 换成 openssl

**Comment by Neutralization** [comment]
> 建议把默认的 wolfssl 换成 openssl

Symbol: DEFAULT_libustream-wolfssl [=y]
  │ Type  : bool
  │ Defined at tmp/.config-target.in:199510
  │ Selected by [y]:
  │   - TARGET_rockchip_armv8_DEVICE_friendlyarm_nanopi-r2s [=y] && <choice> && TARGET_rockchip_armv8 [=y]

.config-target.in:199510
===================================
	config DEFAULT_libustream-wolfssl
		bool

	config MODULE_DEFAULT_libustream-wolfssl
		tristate
		depends on TARGET_PER_DEVICE_ROOTFS
		depends on m
		default m if DEFAULT_libustream-wolfssl
		select PACKAGE_libustream-wolfssl
===================================

看了下是target里的依赖，这部分不太敢直接动，目前改unblockneteasemusic的Makefile编译完是能正常用的。
不太清楚wolfssl和openssl的区别，只是反馈一下。

**Comment by 1715173329** [comment]
官方那边 libustream 的 Makefile 写得实在是不太行，三个库兼容起来很麻烦。
他们为了所谓 size 切到了 wolfssl，但事实上却仍有一大堆应用依赖 openssl，最后反而导致实际占用增大了。
这个更改一下也基本没有影响，我个人推荐把默认的 libustream-wolfssl 改为 libustream-openssl。
